title: Sensorium Festival 2020
author:
  name: Sensorium Festival
  email: hello@sensorium.is
ticket_url: https://ti.to/sensorium/sensorium-festival-2020
metadata:
    description: Sensorium is the first Slovak festival making sense of creative technology. Sensorium gathers an international community of artists, designers, technologists and entrepreneurs for its conference programme, interactive exhibition, live performances and cross-disciplinary workshops.
    keywords: sensorium, conference, art, design, performance, technology, digital, bratislava, creative technology
    author: Sensorium Festival
    'og:title': Sensorium Festival 2020
    'og:description': Sensorium is the first Slovak festival making sense of creative technology. Sensorium gathers an international community of artists, designers, technologists and entrepreneurs for its conference programme, interactive exhibition, live performances and cross-disciplinary workshops.
    'og:type': website
    'og:url': http://sensorium.is/
    'og:site_name': Sensorium Festival 2020
    'og:image': http://sensorium.is/user/themes/imaginarious/images/social/sensorium-2019.jpg
    'og:locale': en_GB
    'og:locale:alternate': sk_SK
    'twitter:card' : summary_large_image
menu:
   - text: Map
     url: /map
     classes: 'external link grow ba-l bw1 mt-1 mh2'
     newTab: false
   - text: Tickets
     url: https://ti.to/sensorium-festival-2019/sensorium-2019
     classes: 'external link grow ba-l bw1 mt-1 mh2'
     newTab: true
redirects:
    '/feedback': https://phivk.typeform.com/to/BgibRF
#  '/redirect-test': '/'                         # Redirect test goes to home page
#  '/old/(.*)': '/new/$1'                        # Would redirect /old/my-page to /new/my-page